### ISSUE TITLE
游戏类的网盘链接失效了

### ISSUE THREAD

**Issue by Weststreet** [lxxlxx888/MacApps#6]
你好 游戏类的网盘链接失效了

**Comment by lxxlxx888** [comment]
你好，现在百度对链接管制很严，经常失效.可以通过我留的邮箱发邮件给我，我会发新的链接给你.

**Comment by Weststreet** [comment]
@lxxlxx888 好哒 谢谢

**Comment by lxxlxx888** [comment]
https://pan.baidu.com/wap/home?dir=%2F%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90%2F#list/path=%2F%E6%88%91%E7%9A%84%E8%B5%84%E6%BA%90%2Fm%E6%88%8F&page=1

看看行吗？
